// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { QuizProvider } from "@/lib/quiz-context";
import { RoutineProvider } from "@/lib/routine-context";

export const metadata: Metadata = {
  title: "HairInsight - Análise Capilar Inteligente",
  description: "Seu assistente pessoal de cuidados capilares com IA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className="font-inter antialiased bg-[#0D0D0D] text-white"
      >
        <QuizProvider>
          <RoutineProvider>
            {children}
          </RoutineProvider>
        </QuizProvider>
      </body>
    </html>
  );
}
