// Generated by Lasy AI - https://lasy.ai
import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "./globals.css";
import { QuizProvider } from "@/lib/quiz-context";
import { RoutineProvider } from "@/lib/routine-context";
import PWAInstall from "@/components/PWAInstall";

export const metadata: Metadata = {
  title: "HairInsight - Análise Capilar Inteligente",
  description: "Seu assistente pessoal de cuidados capilares com IA",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "HairInsight",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  themeColor: "#0D0D0D",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <Script src="/register-sw.js" strategy="afterInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/icon.svg" />
      </head>
      <body
        className="font-inter antialiased bg-[#0D0D0D] text-white"
      >
        <QuizProvider>
          <RoutineProvider>
            {children}
            <PWAInstall />
          </RoutineProvider>
        </QuizProvider>
      </body>
    </html>
  );
}
